<?php

namespace AppBundle\Repository;

/**
 * RevistaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RevistaRepository extends \Doctrine\ORM\EntityRepository
{
}
