<?php

namespace AppBundle\Repository;

/**
 * TextoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TextoRepository extends \Doctrine\ORM\EntityRepository
{
    public function buscarPorTag($tag)
    {
        return $this->getEntityManager()

        ->createQuery("SELECT te 
                                  from AppBundle:Texto te 
                                  JOIN te.tags ta
                                   WHERE ta.nombre= :price")->setParameter('price', $tag )

        ->getResult();
    }

}
