services:
    twig.extension.date:
        class: Twig_Extensions_Extension_Date
        tags:
            - { name: twig.extension }

    app.form.registration:
        class: Trascastro\UserBundle\Form\UserRegistrationType
        tags:
             - { name: form.type, alias: user_bundle_user_registration_type }

    app.form.profile:
            class: Trascastro\UserBundle\Form\UserProfileType
            tags:
                 - { name: form.type, alias: user_bundle_user_profile_type }

    app.form.texto:
                class: AppBundle\Form\TextoType
                tags:
                     - { name: form.type, alias: app_bundle_text_type }

    authentication.handler.login_success_handler:
            class:  Trascastro\UserBundle\Security\LoginSuccessHandler
            arguments:  ['@router', '@security.authorization_checker']
